version: '3.8'

services:
  mpt-app:
    build: .
    ports:
      - "10000:10000"
    environment:
      - PORT=10000
    volumes:
      # Optional: Mount for development
      # - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
