[server]
port = 10000
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

# [theme]
# primaryColor = "#1f77b4"
# backgroundColor = "#ffffff"
# secondaryBackgroundColor = "#f0f2f6"
# textColor = "#262730"

[global]
developmentMode = false
